spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: Cloud-Native-Web
  security:
    user:
      name: disabled
      password: disabled
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: ${DB_CONN_TIMEOUT_MS:5000}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jackson:
    deserialization:
      fail-on-unknown-properties: true

logging:
  file:
    name: ${APP_DIR}/log/app.log
  level:
    root: INFO
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: OFF
    org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver: OFF
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger - %msg%n"

aws:
  region: ${AWS_REGION}
  s3:
    bucket: ${S3_BUCKET}
  sns:
    topicArn: arn:aws:sns:${AWS_REGION}:${ACCOUNT_ID}:${TOPIC_NAME}

server:
  port: ${SERVER_PORT:8081}
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never


management:
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: false
    export:
      statsd:
        enabled: true
        flavor: etsy
        host: 127.0.0.1
        port: 8125
        polling-frequency: 10s
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always